// <auto-generated />
namespace MySQLTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddBook_TitleYomigana : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBook_TitleYomigana));
        
        string IMigrationMetadata.Id
        {
            get { return "201508211709414_AddBook_TitleYomigana"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
